project:
  type: website
  output-dir: docs

website:
  title: "Områdesskydd och havsplanering"
  search: false
  sidebar: false
  navbar:
    right:
      - href: index.html 
        text: Home
      - href: shiny.qmd
        text: Shiny
      - href: rapporter.qmd
        text: Rapporter
        
format:
  html:
    theme: cosmo
    css: styles.css
    anchor-sections: false
    toc: false

editor: visual